apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Klaxon9718/hybrid-network-integration.git
    targetRevision: main
    path: msa/aws-msa-full-ui-cleaned/msa/k8s/k8s-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true